mysql:
    ip: FILL
    user: FILL
    pass: FILL
    schema: FILL
    prefix: 'dom'
permissions:
    admin: 'domination.admin'
    player: 'domination.player'
    moderator: 'domination.moderator'
game: none
lobby: domination
lobbytime: 25
whitelisted:
    - 'leave'
    - 'domination'